services:
  - type: web
    name: transport-facility
    env: static
    buildCommand: npm install && ng build --configuration production
    staticPublishPath: dist/transport-facility/browser
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
